# Generated by Django 5.1.2 on 2024-10-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransferEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tx_hash', models.CharField(max_length=255, unique=True)),
                ('token_id', models.CharField(max_length=255)),
                ('from_address', models.CharField(max_length=255)),
                ('to_address', models.CharField(max_length=255)),
                ('block_number', models.IntegerField()),
            ],
        ),
    ]
